-- =====================================================================
-- WicketWise — COMPLETE BACKEND SETUP (consolidated)
-- =====================================================================
-- Generated by concatenating, in dependency order:
--   db/schema.sql -> db/02-roles-and-profiles.sql -> db/03-teams-competitions.sql
--   -> db/04-scoring-engine.sql -> db/05-integrity-notifications.sql
-- plus a venues table (used by src/features/venues.ts) that wasn't defined
-- in any of the numbered files.
--
-- Paste this whole file into the Supabase SQL editor and run it once.
-- Every statement is idempotent, so re-running it is safe.
--
-- NOTE: db/phase-1-foundation.sql was intentionally NOT included here.
-- It's an alternate/earlier draft of the foundation layer that uses
-- different column names (e.g. profiles.player_role, captain_requests.reason)
-- than what the current frontend code actually queries (primary_role,
-- secondary_role, message, onboarding_complete — see src/lib/types.ts and
-- src/features/people.ts). Running it alongside these files would silently
-- overwrite handle_new_user()/sync_player_from_profile() with a version the
-- app doesn't match. If that file is meant to replace this chain instead,
-- say so and I'll rebuild this script around it.
-- =====================================================================


-- ======================================================================
-- SOURCE FILE 1: db/schema.sql
-- ======================================================================

-- WicketWise — core schema (run this in your Supabase project's SQL editor)
-- Single source of truth: public.deliveries. Every statistic is a derived view.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- roles
do $$ begin
  create type public.app_role as enum ('admin', 'scorer', 'captain', 'player');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now()
);
grant select, insert, update on public.profiles to authenticated;
grant select on public.profiles to anon;
grant all on public.profiles to service_role;
alter table public.profiles enable row level security;
drop policy if exists "profiles readable" on public.profiles;
create policy "profiles readable" on public.profiles for select using (true);
drop policy if exists "own profile insert" on public.profiles;
create policy "own profile insert" on public.profiles for insert to authenticated with check (auth.uid() = id);
drop policy if exists "own profile update" on public.profiles;
create policy "own profile update" on public.profiles for update to authenticated using (auth.uid() = id);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  unique (user_id, role)
);
grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
alter table public.user_roles enable row level security;
drop policy if exists "read own roles" on public.user_roles;
create policy "read own roles" on public.user_roles for select to authenticated using (auth.uid() = user_id);

create or replace function public.has_role(_user_id uuid, _role public.app_role)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.user_roles where user_id = _user_id and role = _role)
$$;

-- auto-create a profile row on signup
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------- players
create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  nickname text,
  batting_style text,
  bowling_style text,
  role text,
  photo_url text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.players to authenticated;
grant select on public.players to anon;
grant all on public.players to service_role;
alter table public.players enable row level security;
drop policy if exists "players readable" on public.players;
create policy "players readable" on public.players for select using (true);
drop policy if exists "players insert" on public.players;
create policy "players insert" on public.players for insert to authenticated with check (auth.uid() = created_by);
drop policy if exists "players update" on public.players;
create policy "players update" on public.players for update to authenticated
  using (auth.uid() = created_by or auth.uid() = user_id or public.has_role(auth.uid(), 'admin'));
drop policy if exists "players delete" on public.players;
create policy "players delete" on public.players for delete to authenticated
  using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));

-- ---------------------------------------------------------------- teams
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_name text not null default '',
  logo_url text,
  home_ground text,
  captain_player_id uuid references public.players(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.teams to authenticated;
grant select on public.teams to anon;
grant all on public.teams to service_role;
alter table public.teams enable row level security;
drop policy if exists "teams readable" on public.teams;
create policy "teams readable" on public.teams for select using (true);
drop policy if exists "teams insert" on public.teams;
create policy "teams insert" on public.teams for insert to authenticated with check (auth.uid() = created_by);
drop policy if exists "teams update" on public.teams;
create policy "teams update" on public.teams for update to authenticated
  using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));
drop policy if exists "teams delete" on public.teams;
create policy "teams delete" on public.teams for delete to authenticated
  using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));

create table if not exists public.team_members (
  team_id uuid not null references public.teams(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  jersey_number int,
  primary key (team_id, player_id)
);
grant select, insert, update, delete on public.team_members to authenticated;
grant select on public.team_members to anon;
grant all on public.team_members to service_role;
alter table public.team_members enable row level security;
drop policy if exists "team members readable" on public.team_members;
create policy "team members readable" on public.team_members for select using (true);
drop policy if exists "team members write" on public.team_members;
create policy "team members write" on public.team_members for all to authenticated
  using (exists (select 1 from public.teams t where t.id = team_id and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin'))))
  with check (exists (select 1 from public.teams t where t.id = team_id and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin'))));

-- ---------------------------------------------------------------- matches
create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  title text,
  venue text,
  match_date timestamptz not null default now(),
  overs_per_innings int not null default 20,
  team_a_id uuid not null references public.teams(id) on delete cascade,
  team_b_id uuid not null references public.teams(id) on delete cascade,
  toss_winner_team_id uuid references public.teams(id) on delete set null,
  toss_decision text check (toss_decision in ('bat','bowl')),
  status text not null default 'scheduled' check (status in ('scheduled','live','completed','abandoned')),
  result_text text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.matches to authenticated;
grant select on public.matches to anon;
grant all on public.matches to service_role;
alter table public.matches enable row level security;
drop policy if exists "matches readable" on public.matches;
create policy "matches readable" on public.matches for select using (true);
drop policy if exists "matches insert" on public.matches;
create policy "matches insert" on public.matches for insert to authenticated with check (auth.uid() = created_by);
drop policy if exists "matches update" on public.matches;
create policy "matches update" on public.matches for update to authenticated
  using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));
drop policy if exists "matches delete" on public.matches;
create policy "matches delete" on public.matches for delete to authenticated
  using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));

create table if not exists public.innings (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  innings_number int not null default 1,
  batting_team_id uuid not null references public.teams(id) on delete cascade,
  bowling_team_id uuid not null references public.teams(id) on delete cascade,
  is_closed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (match_id, innings_number)
);
grant select, insert, update, delete on public.innings to authenticated;
grant select on public.innings to anon;
grant all on public.innings to service_role;
alter table public.innings enable row level security;
drop policy if exists "innings readable" on public.innings;
create policy "innings readable" on public.innings for select using (true);
drop policy if exists "innings write" on public.innings;
create policy "innings write" on public.innings for all to authenticated
  using (exists (select 1 from public.matches m where m.id = match_id and (m.created_by = auth.uid() or public.has_role(auth.uid(), 'admin') or public.has_role(auth.uid(), 'scorer'))))
  with check (exists (select 1 from public.matches m where m.id = match_id and (m.created_by = auth.uid() or public.has_role(auth.uid(), 'admin') or public.has_role(auth.uid(), 'scorer'))));

-- ------------------------------------------------- deliveries (source of truth)
create table if not exists public.deliveries (
  id uuid primary key default gen_random_uuid(),
  innings_id uuid not null references public.innings(id) on delete cascade,
  over_number int not null,
  ball_number int not null,
  striker_id uuid references public.players(id) on delete set null,
  non_striker_id uuid references public.players(id) on delete set null,
  bowler_id uuid references public.players(id) on delete set null,
  runs_off_bat int not null default 0,
  extra_type text check (extra_type in ('wide','noball','bye','legbye','penalty')),
  extra_runs int not null default 0,
  wicket_type text check (wicket_type in ('bowled','caught','lbw','run out','stumped','hit wicket','retired')),
  dismissed_player_id uuid references public.players(id) on delete set null,
  fielder_id uuid references public.players(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists deliveries_innings_idx on public.deliveries(innings_id, over_number, ball_number);
grant select, insert, update, delete on public.deliveries to authenticated;
grant select on public.deliveries to anon;
grant all on public.deliveries to service_role;
alter table public.deliveries enable row level security;
drop policy if exists "deliveries readable" on public.deliveries;
create policy "deliveries readable" on public.deliveries for select using (true);
drop policy if exists "deliveries write" on public.deliveries;
create policy "deliveries write" on public.deliveries for all to authenticated
  using (exists (
    select 1 from public.innings i join public.matches m on m.id = i.match_id
    where i.id = innings_id and (m.created_by = auth.uid() or public.has_role(auth.uid(), 'admin') or public.has_role(auth.uid(), 'scorer'))))
  with check (exists (
    select 1 from public.innings i join public.matches m on m.id = i.match_id
    where i.id = innings_id and (m.created_by = auth.uid() or public.has_role(auth.uid(), 'admin') or public.has_role(auth.uid(), 'scorer'))));

-- ---------------------------------------------------------------- derived stats
-- Nothing below is ever written by hand. Every number comes from deliveries.

create or replace view public.innings_totals
with (security_invoker = true) as
select
  i.id as innings_id,
  i.match_id,
  i.innings_number,
  i.batting_team_id,
  i.bowling_team_id,
  coalesce(sum(d.runs_off_bat + d.extra_runs), 0)::int as runs,
  count(d.id) filter (where d.wicket_type is not null and d.wicket_type <> 'retired')::int as wickets,
  count(d.id) filter (where d.extra_type is null or d.extra_type in ('bye','legbye','penalty'))::int as legal_balls
from public.innings i
left join public.deliveries d on d.innings_id = i.id
group by i.id;
grant select on public.innings_totals to anon, authenticated;

create or replace view public.batting_stats
with (security_invoker = true) as
select
  p.id as player_id,
  p.full_name,
  count(distinct d.innings_id)::int as innings_played,
  coalesce(sum(d.runs_off_bat), 0)::int as runs,
  count(d.id) filter (where d.extra_type is null or d.extra_type = 'noball')::int as balls_faced,
  count(*) filter (where d.runs_off_bat = 4)::int as fours,
  count(*) filter (where d.runs_off_bat = 6)::int as sixes,
  (select count(*) from public.deliveries x
    where x.dismissed_player_id = p.id and x.wicket_type is not null and x.wicket_type <> 'retired')::int as dismissals
from public.players p
left join public.deliveries d on d.striker_id = p.id
group by p.id;
grant select on public.batting_stats to anon, authenticated;

create or replace view public.bowling_stats
with (security_invoker = true) as
select
  p.id as player_id,
  p.full_name,
  count(distinct d.innings_id)::int as innings_bowled,
  count(d.id) filter (where d.extra_type is null or d.extra_type in ('bye','legbye'))::int as legal_balls,
  coalesce(sum(d.runs_off_bat + case when d.extra_type in ('wide','noball','penalty') then d.extra_runs else 0 end), 0)::int as runs_conceded,
  count(*) filter (where d.wicket_type in ('bowled','caught','lbw','stumped','hit wicket'))::int as wickets
from public.players p
left join public.deliveries d on d.bowler_id = p.id
group by p.id;
grant select on public.bowling_stats to anon, authenticated;

-- optional: enable realtime for live scoring
do $$ begin
  alter publication supabase_realtime add table public.deliveries;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.matches;
exception when duplicate_object then null; end $$;


-- ======================================================================
-- SOURCE FILE 2: db/02-roles-and-profiles.sql
-- ======================================================================

-- WicketWise — Phase 2: roles, player profiles, captain approval, scoring permissions
-- Run this AFTER db/schema.sql in your Supabase SQL editor. Safe to re-run.

-- ---------------------------------------------------------------- enums
do $$ begin
  create type public.player_status as enum
    ('registered','available','unavailable','selected','playing','suspended');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.request_status as enum ('pending','approved','rejected');
exception when duplicate_object then null; end $$;

-- ------------------------------------------------- profiles: personal + cricket
alter table public.profiles
  add column if not exists email text,
  add column if not exists phone text,
  add column if not exists date_of_birth date,
  add column if not exists gender text,
  add column if not exists nationality text,
  add column if not exists city text,
  add column if not exists batting_style text,
  add column if not exists bowling_style text,
  add column if not exists primary_role text,
  add column if not exists secondary_role text,
  add column if not exists jersey_number int,
  add column if not exists preferred_position text,
  add column if not exists experience text,
  add column if not exists bio text,
  add column if not exists is_available boolean not null default false,
  add column if not exists status public.player_status not null default 'registered',
  add column if not exists onboarding_step int not null default 1,
  add column if not exists onboarding_complete boolean not null default false;

-- every signup is a player
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), new.email)
  on conflict (id) do nothing;
  insert into public.user_roles (user_id, role) values (new.id, 'player')
  on conflict (user_id, role) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

-- backfill for accounts created before this migration
insert into public.user_roles (user_id, role)
select id, 'player' from auth.users on conflict (user_id, role) do nothing;

-- admins may moderate any profile (suspend, correct data)
drop policy if exists "admin profile update" on public.profiles;
create policy "admin profile update" on public.profiles for update to authenticated
  using (public.has_role(auth.uid(), 'admin')) with check (true);

-- ------------------------------------------------- keep a player row per user
-- Rosters, scorecards and stats all key off public.players, so a completed
-- profile mirrors itself into that table.
create or replace function public.sync_player_from_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.onboarding_complete then
    if exists (select 1 from public.players where user_id = new.id) then
      update public.players set
        full_name = coalesce(nullif(new.full_name, ''), full_name),
        batting_style = new.batting_style,
        bowling_style = new.bowling_style,
        role = new.primary_role,
        photo_url = new.avatar_url
      where user_id = new.id;
    else
      insert into public.players (user_id, full_name, batting_style, bowling_style, role, photo_url, created_by)
      values (new.id, coalesce(nullif(new.full_name, ''), 'Player'), new.batting_style,
              new.bowling_style, new.primary_role, new.avatar_url, new.id);
    end if;
  end if;
  return new;
end $$;
drop trigger if exists on_profile_synced on public.profiles;
create trigger on_profile_synced after insert or update on public.profiles
  for each row execute function public.sync_player_from_profile();

-- ---------------------------------------------------------------- roles read
-- Captain badges and rosters are public information.
drop policy if exists "read own roles" on public.user_roles;
drop policy if exists "roles readable" on public.user_roles;
create policy "roles readable" on public.user_roles for select using (true);
grant select on public.user_roles to anon;

-- ------------------------------------------------- captain requests
create table if not exists public.captain_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  message text,
  status public.request_status not null default 'pending',
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create unique index if not exists captain_requests_one_pending
  on public.captain_requests(user_id) where status = 'pending';
grant select, insert on public.captain_requests to authenticated;
grant update on public.captain_requests to authenticated;
grant all on public.captain_requests to service_role;
alter table public.captain_requests enable row level security;
drop policy if exists "own or admin request read" on public.captain_requests;
create policy "own or admin request read" on public.captain_requests for select to authenticated
  using (auth.uid() = user_id or public.has_role(auth.uid(), 'admin'));
drop policy if exists "own request insert" on public.captain_requests;
create policy "own request insert" on public.captain_requests for insert to authenticated
  with check (auth.uid() = user_id and status = 'pending');
drop policy if exists "admin request review" on public.captain_requests;
create policy "admin request review" on public.captain_requests for update to authenticated
  using (public.has_role(auth.uid(), 'admin')) with check (public.has_role(auth.uid(), 'admin'));

-- approval grants the captain role; rejection revokes it
create or replace function public.apply_captain_request()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'approved' and old.status <> 'approved' then
    insert into public.user_roles (user_id, role) values (new.user_id, 'captain')
    on conflict (user_id, role) do nothing;
  elsif new.status = 'rejected' and old.status = 'approved' then
    delete from public.user_roles where user_id = new.user_id and role = 'captain';
  end if;
  new.reviewed_at := now();
  return new;
end $$;
drop trigger if exists on_captain_request_reviewed on public.captain_requests;
create trigger on_captain_request_reviewed before update on public.captain_requests
  for each row execute function public.apply_captain_request();

-- ------------------------------------------------- scoring permissions
-- A temporary, match-scoped grant. It expires the moment the match completes.
create table if not exists public.scoring_permissions (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  granted_by uuid references auth.users(id) on delete set null,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (match_id, user_id)
);
grant select, insert, update, delete on public.scoring_permissions to authenticated;
grant all on public.scoring_permissions to service_role;
alter table public.scoring_permissions enable row level security;

create or replace function public.is_match_manager(_user_id uuid, _match_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.has_role(_user_id, 'admin')
      or exists (select 1 from public.matches m where m.id = _match_id and m.created_by = _user_id)
$$;

/** True when the user may write deliveries for this match right now. */
create or replace function public.can_score_match(_user_id uuid, _match_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_match_manager(_user_id, _match_id)
      or exists (
        select 1 from public.scoring_permissions sp
        join public.matches m on m.id = sp.match_id
        where sp.match_id = _match_id
          and sp.user_id = _user_id
          and sp.revoked = false
          and m.status in ('scheduled','live')   -- auto-expires on completion
      )
$$;

drop policy if exists "scoring permissions readable" on public.scoring_permissions;
create policy "scoring permissions readable" on public.scoring_permissions for select to authenticated
  using (auth.uid() = user_id or public.is_match_manager(auth.uid(), match_id));
drop policy if exists "scoring permissions manage" on public.scoring_permissions;
create policy "scoring permissions manage" on public.scoring_permissions for all to authenticated
  using (public.is_match_manager(auth.uid(), match_id))
  with check (public.is_match_manager(auth.uid(), match_id));

-- ------------------------------------------------- tighten write policies
-- Only captains and admins create competitions and teams.
drop policy if exists "teams insert" on public.teams;
create policy "teams insert" on public.teams for insert to authenticated
  with check (auth.uid() = created_by
              and (public.has_role(auth.uid(), 'captain') or public.has_role(auth.uid(), 'admin')));

drop policy if exists "matches insert" on public.matches;
create policy "matches insert" on public.matches for insert to authenticated
  with check (auth.uid() = created_by
              and (public.has_role(auth.uid(), 'captain') or public.has_role(auth.uid(), 'admin')));

-- Scoring writes are match-scoped, not role-wide.
drop policy if exists "innings write" on public.innings;
create policy "innings write" on public.innings for all to authenticated
  using (public.can_score_match(auth.uid(), match_id))
  with check (public.can_score_match(auth.uid(), match_id));

drop policy if exists "deliveries write" on public.deliveries;
create policy "deliveries write" on public.deliveries for all to authenticated
  using (exists (select 1 from public.innings i
                 where i.id = innings_id and public.can_score_match(auth.uid(), i.match_id)))
  with check (exists (select 1 from public.innings i
                 where i.id = innings_id and public.can_score_match(auth.uid(), i.match_id)));

-- ------------------------------------------------- avatars bucket
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "avatars are public" on storage.objects;
create policy "avatars are public" on storage.objects for select
  using (bucket_id = 'avatars');
drop policy if exists "own avatar write" on storage.objects;
create policy "own avatar write" on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
drop policy if exists "own avatar update" on storage.objects;
create policy "own avatar update" on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

-- ------------------------------------------------- make yourself an admin
-- Run once, with your own email:
-- insert into public.user_roles (user_id, role)
-- select id, 'admin' from auth.users where email = 'you@example.com'
-- on conflict (user_id, role) do nothing;


-- ======================================================================
-- SOURCE FILE 3: db/03-teams-competitions.sql
-- ======================================================================

-- WicketWise — Phase 4 & 5: teams, selection, match lifecycle, series & tournaments.
-- Run AFTER schema.sql and 02-roles-and-profiles.sql.
-- Everything numeric here is DERIVED from deliveries. Nothing is typed in by hand.

-- ---------------------------------------------------------------- enums
do $$ begin
  create type public.invite_status as enum ('pending','accepted','declined','cancelled');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.match_state as enum
    ('DRAFT','SUBMITTED','APPROVED','SQUAD_SELECTION','READY','TOSS','LIVE','COMPLETED','VERIFIED','ARCHIVED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.approval_status as enum ('draft','submitted','approved','rejected','changes_requested');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.tournament_format as enum ('league','knockout','group_knockout');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------- teams
alter table public.teams
  add column if not exists description text,
  add column if not exists city text,
  add column if not exists country text,
  add column if not exists vice_captain_player_id uuid references public.players(id) on delete set null,
  add column if not exists primary_color text default '#0f7a4d',
  add column if not exists secondary_color text default '#d9a441',
  add column if not exists founded_year int,
  add column if not exists is_active boolean not null default true;

-- --------------------------------------------------- two-sided selection
create table if not exists public.team_invitations (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  invited_by uuid references auth.users(id) on delete set null,
  status public.invite_status not null default 'pending',
  message text,
  created_at timestamptz not null default now(),
  responded_at timestamptz
);
create unique index if not exists team_invitations_pending_uniq
  on public.team_invitations(team_id, player_id) where status = 'pending';
grant select, insert, update, delete on public.team_invitations to authenticated;
grant select on public.team_invitations to anon;
grant all on public.team_invitations to service_role;
alter table public.team_invitations enable row level security;

drop policy if exists "invitations readable" on public.team_invitations;
create policy "invitations readable" on public.team_invitations for select using (true);

drop policy if exists "invitations created by team managers" on public.team_invitations;
create policy "invitations created by team managers" on public.team_invitations
  for insert to authenticated with check (
    exists (select 1 from public.teams t where t.id = team_id
            and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin')))
  );

-- The invited player answers; the captain may cancel.
drop policy if exists "invitations answered by player or manager" on public.team_invitations;
create policy "invitations answered by player or manager" on public.team_invitations
  for update to authenticated using (
    exists (select 1 from public.players p where p.id = player_id and p.user_id = auth.uid())
    or exists (select 1 from public.teams t where t.id = team_id
               and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin')))
  );

-- Accepting is the ONLY way a player lands on a roster.
create or replace function public.handle_invitation_response()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'accepted' and old.status <> 'accepted' then
    insert into public.team_members (team_id, player_id)
    values (new.team_id, new.player_id)
    on conflict (team_id, player_id) do nothing;
    new.responded_at := now();
  elsif new.status <> old.status then
    new.responded_at := now();
  end if;
  return new;
end $$;
drop trigger if exists on_invitation_response on public.team_invitations;
create trigger on_invitation_response before update on public.team_invitations
  for each row execute function public.handle_invitation_response();

-- ---------------------------------------------------------------- series
create table if not exists public.series (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  team_a_id uuid references public.teams(id) on delete set null,
  team_b_id uuid references public.teams(id) on delete set null,
  match_count int not null default 3,
  start_date date,
  end_date date,
  points_per_win int not null default 2,
  points_per_tie int not null default 1,
  approval_status public.approval_status not null default 'draft',
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.series to authenticated;
grant select on public.series to anon;
grant all on public.series to service_role;
alter table public.series enable row level security;

drop policy if exists "approved series are public" on public.series;
create policy "approved series are public" on public.series for select using (
  approval_status = 'approved' or created_by = auth.uid() or public.has_role(auth.uid(), 'admin')
);
drop policy if exists "captains create series" on public.series;
create policy "captains create series" on public.series for insert to authenticated
  with check (created_by = auth.uid()
    and (public.has_role(auth.uid(), 'captain') or public.has_role(auth.uid(), 'admin')));
drop policy if exists "series owner or admin updates" on public.series;
create policy "series owner or admin updates" on public.series for update to authenticated
  using (created_by = auth.uid() or public.has_role(auth.uid(), 'admin'));
drop policy if exists "series owner or admin deletes" on public.series;
create policy "series owner or admin deletes" on public.series for delete to authenticated
  using (created_by = auth.uid() or public.has_role(auth.uid(), 'admin'));

-- ------------------------------------------------------------ tournaments
create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo_url text,
  description text,
  organizer text,
  start_date date,
  end_date date,
  venue text,
  format public.tournament_format not null default 'league',
  team_count int not null default 8,
  rules text,
  points_per_win int not null default 2,
  points_per_tie int not null default 1,
  points_per_loss int not null default 0,
  approval_status public.approval_status not null default 'draft',
  review_note text,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
grant select, insert, update, delete on public.tournaments to authenticated;
grant select on public.tournaments to anon;
grant all on public.tournaments to service_role;
alter table public.tournaments enable row level security;

drop policy if exists "approved tournaments are public" on public.tournaments;
create policy "approved tournaments are public" on public.tournaments for select using (
  approval_status = 'approved' or created_by = auth.uid() or public.has_role(auth.uid(), 'admin')
);
drop policy if exists "captains create tournaments" on public.tournaments;
create policy "captains create tournaments" on public.tournaments for insert to authenticated
  with check (created_by = auth.uid()
    and (public.has_role(auth.uid(), 'captain') or public.has_role(auth.uid(), 'admin')));
drop policy if exists "tournament owner or admin updates" on public.tournaments;
create policy "tournament owner or admin updates" on public.tournaments for update to authenticated
  using (created_by = auth.uid() or public.has_role(auth.uid(), 'admin'));
drop policy if exists "tournament owner or admin deletes" on public.tournaments;
create policy "tournament owner or admin deletes" on public.tournaments for delete to authenticated
  using (created_by = auth.uid() or public.has_role(auth.uid(), 'admin'));

create table if not exists public.tournament_teams (
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  group_name text,
  primary key (tournament_id, team_id)
);
grant select, insert, update, delete on public.tournament_teams to authenticated;
grant select on public.tournament_teams to anon;
grant all on public.tournament_teams to service_role;
alter table public.tournament_teams enable row level security;
drop policy if exists "tournament teams readable" on public.tournament_teams;
create policy "tournament teams readable" on public.tournament_teams for select using (true);
drop policy if exists "tournament teams write" on public.tournament_teams;
create policy "tournament teams write" on public.tournament_teams for all to authenticated
  using (exists (select 1 from public.tournaments t where t.id = tournament_id
                 and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin'))))
  with check (exists (select 1 from public.tournaments t where t.id = tournament_id
                 and (t.created_by = auth.uid() or public.has_role(auth.uid(), 'admin'))));

-- ------------------------------------------------- match lifecycle + config
alter table public.matches
  add column if not exists match_type text default 'friendly',
  add column if not exists start_time text,
  add column if not exists format text default 'T20',
  add column if not exists ball_type text default 'leather',
  add column if not exists innings_count int not null default 2,
  add column if not exists series_id uuid references public.series(id) on delete set null,
  add column if not exists tournament_id uuid references public.tournaments(id) on delete set null,
  add column if not exists stage text,
  add column if not exists group_name text,
  add column if not exists state public.match_state not null default 'DRAFT',
  add column if not exists review_note text;

-- Backfill state for matches created before the lifecycle existed.
update public.matches set state = case
  when status = 'live' then 'LIVE'::public.match_state
  when status = 'completed' then 'COMPLETED'::public.match_state
  when status = 'abandoned' then 'ARCHIVED'::public.match_state
  else 'READY'::public.match_state end
where state = 'DRAFT' and status <> 'scheduled';

-- The state machine. No skipping steps; admins may step back one stage.
create or replace function public.enforce_match_state()
returns trigger language plpgsql set search_path = public as $$
declare
  allowed public.match_state[];
begin
  if new.state = old.state then return new; end if;

  allowed := case old.state
    when 'DRAFT'            then array['SUBMITTED']
    when 'SUBMITTED'        then array['APPROVED','DRAFT']
    when 'APPROVED'         then array['SQUAD_SELECTION']
    when 'SQUAD_SELECTION'  then array['READY']
    when 'READY'            then array['TOSS']
    when 'TOSS'             then array['LIVE']
    when 'LIVE'             then array['COMPLETED']
    when 'COMPLETED'        then array['VERIFIED']
    when 'VERIFIED'         then array['ARCHIVED']
    else array[]::text[]
  end::public.match_state[];

  -- Only admins can approve a submitted match or reject it back to draft.
  if old.state = 'SUBMITTED' and not public.has_role(auth.uid(), 'admin') then
    raise exception 'Only an admin can review a submitted match';
  end if;

  if not (new.state = any(allowed)) then
    raise exception 'Invalid match transition % -> %', old.state, new.state;
  end if;

  new.status := case new.state
    when 'LIVE' then 'live'
    when 'COMPLETED' then 'completed'
    when 'VERIFIED' then 'completed'
    when 'ARCHIVED' then 'completed'
    else 'scheduled' end;

  return new;
end $$;
drop trigger if exists on_match_state_change on public.matches;
create trigger on_match_state_change before update of state on public.matches
  for each row execute function public.enforce_match_state();

-- Scoring is only legal while the match is actually live.
create or replace function public.can_score_match(_user_id uuid, _match_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.matches m
    where m.id = _match_id
      and m.state not in ('COMPLETED','VERIFIED','ARCHIVED')
      and (
        m.created_by = _user_id
        or public.has_role(_user_id, 'admin')
        or exists (select 1 from public.scoring_permissions sp
                   where sp.match_id = _match_id and sp.user_id = _user_id and sp.revoked = false)
      )
  )
$$;

-- ---------------------------------------------------------- derived results
create or replace view public.match_results
with (security_invoker = true) as
with per_team as (
  select it.match_id, it.batting_team_id as team_id, it.bowling_team_id as opponent_id,
         sum(it.runs)::int as runs_scored, sum(it.legal_balls)::int as balls_faced,
         sum(it.wickets)::int as wickets_lost
  from public.innings_totals it
  group by it.match_id, it.batting_team_id, it.bowling_team_id
)
select
  m.id as match_id,
  m.series_id,
  m.tournament_id,
  m.state,
  a.team_id as team_a_id,
  b.team_id as team_b_id,
  coalesce(a.runs_scored, 0) as team_a_runs,
  coalesce(b.runs_scored, 0) as team_b_runs,
  coalesce(a.balls_faced, 0) as team_a_balls,
  coalesce(b.balls_faced, 0) as team_b_balls,
  case
    when m.state not in ('COMPLETED','VERIFIED','ARCHIVED') then null
    when a.runs_scored is null or b.runs_scored is null then null
    when a.runs_scored > b.runs_scored then a.team_id
    when b.runs_scored > a.runs_scored then b.team_id
    else null
  end as winner_team_id,
  case
    when m.state not in ('COMPLETED','VERIFIED','ARCHIVED') then 'pending'
    when a.runs_scored is null or b.runs_scored is null then 'no_result'
    when a.runs_scored = b.runs_scored then 'tie'
    else 'decided'
  end as outcome
from public.matches m
left join per_team a on a.match_id = m.id and a.team_id = m.team_a_id
left join per_team b on b.match_id = m.id and b.team_id = m.team_b_id;
grant select on public.match_results to anon, authenticated;

-- One row per team per completed match — the base for every table below.
create or replace view public.team_match_lines
with (security_invoker = true) as
select r.match_id, r.series_id, r.tournament_id, r.team_a_id as team_id, r.team_b_id as opponent_id,
       r.team_a_runs as runs_for, r.team_b_runs as runs_against,
       r.team_a_balls as balls_faced, r.team_b_balls as balls_bowled,
       r.winner_team_id, r.outcome
from public.match_results r
union all
select r.match_id, r.series_id, r.tournament_id, r.team_b_id, r.team_a_id,
       r.team_b_runs, r.team_a_runs, r.team_b_balls, r.team_a_balls,
       r.winner_team_id, r.outcome
from public.match_results r;
grant select on public.team_match_lines to anon, authenticated;

create or replace view public.team_stats
with (security_invoker = true) as
select
  t.id as team_id,
  t.name,
  count(l.match_id) filter (where l.outcome <> 'pending')::int as played,
  count(l.match_id) filter (where l.winner_team_id = t.id)::int as won,
  count(l.match_id) filter (where l.outcome = 'decided' and l.winner_team_id <> t.id)::int as lost,
  count(l.match_id) filter (where l.outcome = 'tie')::int as tied,
  count(l.match_id) filter (where l.outcome = 'no_result')::int as no_result,
  coalesce(sum(l.runs_for) filter (where l.outcome <> 'pending'), 0)::int as runs_for,
  coalesce(max(l.runs_for) filter (where l.outcome <> 'pending'), 0)::int as highest_score,
  coalesce(min(l.runs_for) filter (where l.outcome <> 'pending'), 0)::int as lowest_score,
  coalesce(sum(l.balls_faced) filter (where l.outcome <> 'pending'), 0)::int as balls_faced,
  coalesce(sum(l.balls_bowled) filter (where l.outcome <> 'pending'), 0)::int as balls_bowled,
  round(
    case when count(l.match_id) filter (where l.outcome <> 'pending') = 0 then 0
    else 100.0 * count(l.match_id) filter (where l.winner_team_id = t.id)
         / count(l.match_id) filter (where l.outcome <> 'pending') end, 1) as win_pct
from public.teams t
left join public.team_match_lines l on l.team_id = t.id
group by t.id, t.name;
grant select on public.team_stats to anon, authenticated;

create or replace view public.series_standings
with (security_invoker = true) as
select
  s.id as series_id,
  l.team_id,
  count(l.match_id) filter (where l.outcome <> 'pending')::int as played,
  count(l.match_id) filter (where l.winner_team_id = l.team_id)::int as won,
  count(l.match_id) filter (where l.outcome = 'decided' and l.winner_team_id <> l.team_id)::int as lost,
  count(l.match_id) filter (where l.outcome = 'tie')::int as tied,
  count(l.match_id) filter (where l.outcome = 'no_result')::int as no_result,
  (count(l.match_id) filter (where l.winner_team_id = l.team_id) * s.points_per_win
   + count(l.match_id) filter (where l.outcome = 'tie') * s.points_per_tie)::int as points,
  coalesce(sum(l.runs_for), 0)::int as runs_for,
  round(case when coalesce(sum(l.balls_faced), 0) = 0 then 0
        else 6.0 * sum(l.runs_for) / sum(l.balls_faced) end, 2) as run_rate
from public.series s
join public.team_match_lines l on l.series_id = s.id
group by s.id, l.team_id;
grant select on public.series_standings to anon, authenticated;

-- Points table: P, W, L, NR, Pts, NRR — computed, never editable.
create or replace view public.tournament_points
with (security_invoker = true) as
select
  t.id as tournament_id,
  tt.team_id,
  tt.group_name,
  count(l.match_id) filter (where l.outcome <> 'pending')::int as played,
  count(l.match_id) filter (where l.winner_team_id = tt.team_id)::int as won,
  count(l.match_id) filter (where l.outcome = 'decided' and l.winner_team_id <> tt.team_id)::int as lost,
  count(l.match_id) filter (where l.outcome = 'tie')::int as tied,
  count(l.match_id) filter (where l.outcome = 'no_result')::int as no_result,
  (coalesce(count(l.match_id) filter (where l.winner_team_id = tt.team_id), 0) * t.points_per_win
   + coalesce(count(l.match_id) filter (where l.outcome = 'tie'), 0) * t.points_per_tie
   + coalesce(count(l.match_id) filter (where l.outcome = 'decided' and l.winner_team_id <> tt.team_id), 0) * t.points_per_loss
  )::int as points,
  coalesce(sum(l.runs_for), 0)::int as runs_for,
  coalesce(sum(l.runs_against), 0)::int as runs_against,
  round(
    case when coalesce(sum(l.balls_faced), 0) = 0 or coalesce(sum(l.balls_bowled), 0) = 0 then 0
    else (6.0 * sum(l.runs_for) / sum(l.balls_faced)) - (6.0 * sum(l.runs_against) / sum(l.balls_bowled))
    end, 3) as nrr
from public.tournaments t
join public.tournament_teams tt on tt.tournament_id = t.id
left join public.team_match_lines l on l.tournament_id = t.id and l.team_id = tt.team_id
group by t.id, tt.team_id, tt.group_name;
grant select on public.tournament_points to anon, authenticated;

do $$ begin
  alter publication supabase_realtime add table public.team_invitations;
exception when duplicate_object then null; end $$;


-- ======================================================================
-- SOURCE FILE 4: db/04-scoring-engine.sql
-- ======================================================================

-- WicketWise · 04 · Live scoring engine
-- Run after db/schema.sql, db/02-roles-and-profiles.sql and db/03-teams-competitions.sql.

/* ------------------------------------------------------------ deliveries */
alter table public.deliveries
  add column if not exists fielder2_id uuid references public.players(id) on delete set null,
  add column if not exists scored_by uuid references auth.users(id) on delete set null;

-- Extra wicket types required by the scoring engine.
do $$
begin
  begin
    alter table public.deliveries drop constraint if exists deliveries_wicket_type_check;
  exception when others then null;
  end;
  alter table public.deliveries
    add constraint deliveries_wicket_type_check
    check (wicket_type is null or wicket_type in (
      'bowled','caught','lbw','run out','stumped','hit wicket',
      'retired','retired out','obstructing the field'
    ));
end $$;

create index if not exists deliveries_innings_seq_idx
  on public.deliveries (innings_id, over_number, ball_number);
create index if not exists deliveries_fielder_idx on public.deliveries (fielder_id);
create index if not exists deliveries_scored_by_idx on public.deliveries (scored_by);

/* ------------------------------------ scoring permission auto-expiry on complete */
create or replace function public.expire_scoring_permissions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('completed','abandoned') or new.state in ('COMPLETED','VERIFIED','ARCHIVED') then
    update public.scoring_permissions
       set revoked = true
     where match_id = new.id and revoked = false;
  end if;
  return new;
end $$;

drop trigger if exists trg_expire_scoring on public.matches;
create trigger trg_expire_scoring
  after update on public.matches
  for each row execute function public.expire_scoring_permissions();

/* ----------------------------------------------------------- notifications */
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  title text not null,
  body text,
  link text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

grant select, insert, update, delete on public.notifications to authenticated;
grant all on public.notifications to service_role;

alter table public.notifications enable row level security;

drop policy if exists "read own notifications" on public.notifications;
create policy "read own notifications" on public.notifications
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "update own notifications" on public.notifications;
create policy "update own notifications" on public.notifications
  for update to authenticated using (user_id = auth.uid());

drop policy if exists "signed in users can notify" on public.notifications;
create policy "signed in users can notify" on public.notifications
  for insert to authenticated with check (true);

-- Notify a player when they are granted scoring rights for a match.
create or replace function public.notify_scorer_granted()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, kind, title, body, link)
  values (
    new.user_id,
    'scorer_granted',
    'You are the scorer for a match',
    'You now have live-scoring access. It expires when the match is completed.',
    '/matches/' || new.match_id || '/score'
  );
  return new;
end $$;

drop trigger if exists trg_notify_scorer on public.scoring_permissions;
create trigger trg_notify_scorer
  after insert on public.scoring_permissions
  for each row execute function public.notify_scorer_granted();

/* ------------------------------------------------------- correction requests */
create table if not exists public.correction_requests (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  delivery_id uuid references public.deliveries(id) on delete set null,
  requested_by uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  proposed jsonb,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

grant select, insert, update on public.correction_requests to authenticated;
grant all on public.correction_requests to service_role;

alter table public.correction_requests enable row level security;

drop policy if exists "read corrections" on public.correction_requests;
create policy "read corrections" on public.correction_requests
  for select to authenticated
  using (requested_by = auth.uid() or public.has_role(auth.uid(), 'admin'));

drop policy if exists "request corrections" on public.correction_requests;
create policy "request corrections" on public.correction_requests
  for insert to authenticated with check (requested_by = auth.uid());

drop policy if exists "admins review corrections" on public.correction_requests;
create policy "admins review corrections" on public.correction_requests
  for update to authenticated using (public.has_role(auth.uid(), 'admin'));

/* ------------------------------------------------------------- realtime */
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;


-- ======================================================================
-- SOURCE FILE 5: db/05-integrity-notifications.sql
-- ======================================================================

-- WicketWise · 05 · Verification chain, corrections, audit log & notifications
-- Run after db/04-scoring-engine.sql.

/* ------------------------------------------------- match verification chain */
alter table public.matches
  add column if not exists submitted_by uuid references auth.users(id) on delete set null,
  add column if not exists submitted_at timestamptz,
  add column if not exists verified_by uuid references auth.users(id) on delete set null,
  add column if not exists verified_at timestamptz,
  add column if not exists admin_verified_by uuid references auth.users(id) on delete set null,
  add column if not exists admin_verified_at timestamptz,
  add column if not exists requires_admin_verification boolean not null default false,
  add column if not exists stats_official boolean not null default false;

-- Stats become official when the captain verifies, unless the match is flagged
-- for the extra admin step — then only admin verification makes them official.
create or replace function public.sync_stats_official()
returns trigger
language plpgsql
as $$
begin
  new.stats_official := case
    when new.requires_admin_verification then new.admin_verified_at is not null
    else new.verified_at is not null
  end;
  return new;
end $$;

drop trigger if exists trg_stats_official on public.matches;
create trigger trg_stats_official
  before insert or update on public.matches
  for each row execute function public.sync_stats_official();

/* ------------------------------------------------------------- audit logs */
create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_table text not null,
  entity_id uuid,
  match_id uuid references public.matches(id) on delete set null,
  before_value jsonb,
  after_value jsonb,
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_entity_idx on public.audit_logs (entity_table, entity_id);
create index if not exists audit_logs_match_idx on public.audit_logs (match_id);
create index if not exists audit_logs_created_idx on public.audit_logs (created_at desc);

grant select, insert on public.audit_logs to authenticated;
grant all on public.audit_logs to service_role;

alter table public.audit_logs enable row level security;

-- Admins see everything; a captain or scorer can see the trail for their own actions.
drop policy if exists "read audit logs" on public.audit_logs;
create policy "read audit logs" on public.audit_logs
  for select to authenticated
  using (public.has_role(auth.uid(), 'admin') or actor_id = auth.uid());

drop policy if exists "append audit logs" on public.audit_logs;
create policy "append audit logs" on public.audit_logs
  for insert to authenticated with check (actor_id = auth.uid() or actor_id is null);

-- Every delivery edit or removal on a completed match is written to the trail
-- automatically, so nothing can be changed silently.
create or replace function public.audit_delivery_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_match uuid;
begin
  select i.match_id into v_match
    from public.innings i
   where i.id = coalesce(new.innings_id, old.innings_id);

  insert into public.audit_logs (actor_id, action, entity_table, entity_id, match_id, before_value, after_value)
  values (
    auth.uid(),
    tg_op,
    'deliveries',
    coalesce(new.id, old.id),
    v_match,
    case when tg_op = 'INSERT' then null else to_jsonb(old) end,
    case when tg_op = 'DELETE' then null else to_jsonb(new) end
  );
  return coalesce(new, old);
end $$;

drop trigger if exists trg_audit_delivery on public.deliveries;
create trigger trg_audit_delivery
  after update or delete on public.deliveries
  for each row execute function public.audit_delivery_change();

/* --------------------------------------------------- correction requests v2 */
alter table public.correction_requests
  add column if not exists field text,
  add column if not exists current_value text,
  add column if not exists requested_value text,
  add column if not exists applied_at timestamptz,
  add column if not exists review_note text;

/* ----------------------------------------------------- notification helpers */
create or replace function public.notify_user(
  _user_id uuid, _kind text, _title text, _body text, _link text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _user_id is null then return; end if;
  insert into public.notifications (user_id, kind, title, body, link)
  values (_user_id, _kind, _title, _body, _link);
end $$;

create or replace function public.notify_admins(_kind text, _title text, _body text, _link text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.notifications (user_id, kind, title, body, link)
  select ur.user_id, _kind, _title, _body, _link
    from public.user_roles ur
   where ur.role = 'admin';
end $$;

/* ------------------------------------------------ squad selection two-sided */
create or replace function public.notify_invitation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team text;
  v_player_user uuid;
  v_player text;
begin
  select name into v_team from public.teams where id = new.team_id;
  select user_id, full_name into v_player_user, v_player from public.players where id = new.player_id;

  if tg_op = 'INSERT' then
    perform public.notify_user(
      v_player_user, 'team_invitation',
      'Squad invitation from ' || coalesce(v_team, 'a team'),
      'You have been selected. Accept or decline from your profile.',
      '/teams/' || new.team_id
    );
  elsif new.status <> old.status and new.status in ('accepted', 'declined') then
    perform public.notify_user(
      new.invited_by, 'selection_response',
      coalesce(v_player, 'A player') || ' ' || new.status || ' your invitation',
      coalesce(v_team, 'Your team') || ' squad update.',
      '/teams/' || new.team_id
    );
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_invitation on public.team_invitations;
create trigger trg_notify_invitation
  after insert or update on public.team_invitations
  for each row execute function public.notify_invitation();

/* ---------------------------------------------------------- captain requests */
create or replace function public.notify_captain_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.notify_admins(
      'captain_request', 'New captain request',
      'A player has requested captain access.', '/admin'
    );
  elsif new.status <> old.status and new.status in ('approved', 'rejected') then
    perform public.notify_user(
      new.user_id, 'captain_request_reviewed',
      'Captain request ' || new.status,
      case when new.status = 'approved'
        then 'Captain tools are now unlocked in your navigation.'
        else 'An admin reviewed your request.' end,
      '/profile'
    );
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_captain_request on public.captain_requests;
create trigger trg_notify_captain_request
  after insert or update on public.captain_requests
  for each row execute function public.notify_captain_request();

/* ------------------------------------------------- competition approvals */
create or replace function public.notify_competition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kind text := tg_table_name;
  v_link text := '/' || tg_table_name || '/' || new.id;
begin
  if tg_table_name = 'series' then v_link := '/series/' || new.id; end if;
  if tg_table_name = 'tournaments' then v_link := '/tournaments/' || new.id; end if;

  if new.approval_status = 'submitted'
     and (tg_op = 'INSERT' or new.approval_status is distinct from old.approval_status) then
    perform public.notify_admins(
      'competition_submitted',
      'A ' || v_kind || ' needs approval',
      new.name || ' was submitted for review.', '/admin'
    );
  elsif tg_op = 'UPDATE'
        and new.approval_status is distinct from old.approval_status
        and new.approval_status in ('approved', 'rejected', 'changes_requested') then
    perform public.notify_user(
      new.created_by, 'competition_reviewed',
      new.name || ' was ' || replace(new.approval_status, '_', ' '),
      coalesce(new.review_note, 'Reviewed by an admin.'), v_link
    );
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_series on public.series;
create trigger trg_notify_series
  after insert or update on public.series
  for each row execute function public.notify_competition();

drop trigger if exists trg_notify_tournament on public.tournaments;
create trigger trg_notify_tournament
  after insert or update on public.tournaments
  for each row execute function public.notify_competition();

/* --------------------------------------------- match lifecycle notifications */
create or replace function public.notify_match_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text := coalesce(new.title, 'Match');
  v_link text := '/matches/' || new.id;
begin
  if new.state is distinct from old.state then
    if new.state = 'COMPLETED' then
      perform public.notify_user(new.created_by, 'match_result',
        v_title || ' is awaiting your verification',
        'Check the scorecard, then verify it to make the statistics official.', v_link);
    elsif new.state = 'VERIFIED' then
      perform public.notify_user(new.submitted_by, 'match_verified',
        v_title || ' has been verified',
        'The captain accepted the scorecard you submitted.', v_link);
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_match on public.matches;
create trigger trg_notify_match
  after update on public.matches
  for each row execute function public.notify_match_lifecycle();

/* ------------------------------------------- correction request notifications */
create or replace function public.notify_correction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    perform public.notify_admins('correction_filed', 'Correction request filed',
      'A completed match needs a data correction reviewed.', '/admin');
  elsif new.status <> old.status then
    perform public.notify_user(new.requested_by, 'correction_reviewed',
      'Your correction request was ' || new.status,
      coalesce(new.review_note, 'Reviewed by an admin.'),
      '/matches/' || new.match_id);
  end if;
  return new;
end $$;

drop trigger if exists trg_notify_correction on public.correction_requests;
create trigger trg_notify_correction
  after insert or update on public.correction_requests
  for each row execute function public.notify_correction();

/* ---------------------------------------------------------------- realtime */
do $$
begin
  begin
    alter publication supabase_realtime add table public.audit_logs;
  exception when duplicate_object then null;
  end;
end $$;


-- =====================================================================
-- ADDITION: venues table
-- =====================================================================
-- Not present in any of the numbered files above, but required by
-- src/features/venues.ts. Adapted from db/phase-1-foundation.sql to use
-- this chain's public.has_role() helper instead of that file's is_admin().

create table if not exists public.venues (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  city text,
  country text,
  surface text,             -- turf / matting / astro / concrete
  capacity int,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (name, city)
);
grant select, insert, update, delete on public.venues to authenticated;
grant select on public.venues to anon;
grant all on public.venues to service_role;
alter table public.venues enable row level security;

drop policy if exists "venues readable" on public.venues;
create policy "venues readable" on public.venues for select using (true);

drop policy if exists "venues managed by captains" on public.venues;
create policy "venues managed by captains" on public.venues
  for insert to authenticated
  with check (auth.uid() = created_by and (public.has_role(auth.uid(), 'captain') or public.has_role(auth.uid(), 'admin')));

drop policy if exists "venues edited by owner or admin" on public.venues;
create policy "venues edited by owner or admin" on public.venues
  for update to authenticated using (auth.uid() = created_by or public.has_role(auth.uid(), 'admin'));

drop policy if exists "venues deleted by admin" on public.venues;
create policy "venues deleted by admin" on public.venues
  for delete to authenticated using (public.has_role(auth.uid(), 'admin'));

-- =====================================================================
-- BOOTSTRAP YOUR FIRST ADMIN
-- Run once, with your own email, after signing up through the app:
--
--   insert into public.user_roles (user_id, role)
--   select id, 'admin' from auth.users where email = 'you@example.com'
--   on conflict (user_id, role) do nothing;
-- =====================================================================
