/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersPlayerIdRouteImport } from './routes/players.$playerId'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments.$tournamentId'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches.$matchId.index'
import { Route as MatchesMatchIdScoreRouteImport } from './routes/matches.$matchId.score'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/tournaments/$tournamentId',
  path: '/tournaments/$tournamentId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/matches/$matchId/',
  path: '/matches/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdScoreRoute = MatchesMatchIdScoreRouteImport.update({
  id: '/matches/$matchId/score',
  path: '/matches/$matchId/score',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/highlights': typeof HighlightsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/setup': typeof SetupRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/highlights': typeof HighlightsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/setup': typeof SetupRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches': typeof MatchesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/series': typeof SeriesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/live': typeof LiveRoute
  '/highlights': typeof HighlightsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/records': typeof RecordsRoute
  '/scoring': typeof ScoringRoute
  '/setup': typeof SetupRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches/': typeof MatchesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/live'
    | '/highlights'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/records'
    | '/scoring'
    | '/setup'
    | '/players/$playerId'
    | '/series/$seriesId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches/'
    | '/players/'
    | '/series/'
    | '/teams/'
    | '/tournaments/'
    | '/matches/$matchId/score'
    | '/matches/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/live'
    | '/highlights'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/records'
    | '/scoring'
    | '/setup'
    | '/players/$playerId'
    | '/series/$seriesId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches'
    | '/players'
    | '/series'
    | '/teams'
    | '/tournaments'
    | '/matches/$matchId/score'
    | '/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/live'
    | '/highlights'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/rankings'
    | '/records'
    | '/scoring'
    | '/setup'
    | '/players/$playerId'
    | '/series/$seriesId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches/'
    | '/players/'
    | '/series/'
    | '/teams/'
    | '/tournaments/'
    | '/matches/$matchId/score'
    | '/matches/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LiveRoute: typeof LiveRoute
  HighlightsRoute: typeof HighlightsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RankingsRoute: typeof RankingsRoute
  RecordsRoute: typeof RecordsRoute
  ScoringRoute: typeof ScoringRoute
  SetupRoute: typeof SetupRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  MatchesMatchIdScoreRoute: typeof MatchesMatchIdScoreRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/score': {
      id: '/matches/$matchId/score'
      path: '/matches/$matchId/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof MatchesMatchIdScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LiveRoute: LiveRoute,
  HighlightsRoute: HighlightsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RankingsRoute: RankingsRoute,
  RecordsRoute: RecordsRoute,
  ScoringRoute: ScoringRoute,
  SetupRoute: SetupRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  MatchesMatchIdScoreRoute: MatchesMatchIdScoreRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
